github.com:
    users:
        xv7kvhc8gy-cyber:
            oauth_token: ghu_sWgtLl8EIx1LKvdqmX1yi2gFtnJEGX3iAxxU
    oauth_token: ghu_sWgtLl8EIx1LKvdqmX1yi2gFtnJEGX3iAxxU
    user: xv7kvhc8gy-cyber
